--require("presence").setup({
	---- General options
	--neovim_image_text = "Coding in Neovim",
	--main_image = "file",
	--file_assets = {
		--tsx = { "TypeScript", "typescript" },
		--jsx = { "JavaScript", "javascript" },
	--},
--})
